[package]
name = "twinkly-mqtt"
version = "0.4.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
tokio = { version = "1", features = [
	"rt",
	"rt-multi-thread",
	"net",
	"time",
	"macros",
	"sync",
	"signal",
] }
serde = { version = "1.0.178", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
rumqttc = "0.22.0"
anyhow = "1.0.72"
palette = { version = "0.7.2", features = ["serializing"] }
log = "0.4.19"
futures = "0.3.28"
config = "0.13.3"
byteorder = "1.4.3"
reqwest = { version = "0.11", default-features = false, features = [
	"json",
	"rustls-tls",
] }
base64 = "0.21.2"
rand = "0.8.5"
